// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMsfUM-LeLn-opDXzfrPA0zw-VdZgrKhs',
    appId: '1:656034738319:web:1d04fb3e6a5fbb1d1440fa',
    messagingSenderId: '656034738319',
    projectId: 'doctorappointmentapp-d3ce5',
    authDomain: 'doctorappointmentapp-d3ce5.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-d3ce5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdNBTFLvVYvqN5HFqEiEsOeNNeWmuPdZE',
    appId: '1:656034738319:android:381c4538c710f9a01440fa',
    messagingSenderId: '656034738319',
    projectId: 'doctorappointmentapp-d3ce5',
    storageBucket: 'doctorappointmentapp-d3ce5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlvj-f2rqEOMvcMkza_vWE1Oy90_d7tyE',
    appId: '1:656034738319:ios:98cc1c2306dc77261440fa',
    messagingSenderId: '656034738319',
    projectId: 'doctorappointmentapp-d3ce5',
    storageBucket: 'doctorappointmentapp-d3ce5.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlvj-f2rqEOMvcMkza_vWE1Oy90_d7tyE',
    appId: '1:656034738319:ios:98cc1c2306dc77261440fa',
    messagingSenderId: '656034738319',
    projectId: 'doctorappointmentapp-d3ce5',
    storageBucket: 'doctorappointmentapp-d3ce5.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMsfUM-LeLn-opDXzfrPA0zw-VdZgrKhs',
    appId: '1:656034738319:web:1af96afd44ad2b291440fa',
    messagingSenderId: '656034738319',
    projectId: 'doctorappointmentapp-d3ce5',
    authDomain: 'doctorappointmentapp-d3ce5.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-d3ce5.firebasestorage.app',
  );
}
